<?php
class Course_ItemController extends HM_Controller_Action
{

    public function init()
    {
        $this->setEmpty();
        parent::init(); // TODO: Change the autogenerated stub
    }

	const WRAPPER = '/wrapper';

    public function viewAction()
    {
        $this->_helper->getHelper('layout')->disableLayout();
        Zend_Controller_Front::getInstance()->unregisterPlugin('HM_Controller_Plugin_Unmanaged');

        /** @var HM_Lesson_LessonService $lessonService */
        $lessonService = $this->getService('Lesson');
        if ($lessonId = $this->_getParam('lesson_id', 0)) {
            $lesson = $lessonService->getLesson($lessonId);
        }

        $itemId    = $this->_getParam('item_id', 0);
        $subjectId = $this->_getParam('subject_id', $lesson ? $lesson->CID : 0);

        /** @var HM_Course_Item_ItemService $itemService */
        $itemService = $this->getService('CourseItem');

        /** @var HM_Course_Item_ItemModel $item */
        $item = $itemService->fetchRow(['oid = ?' => $itemId]);

        if((get_class($item) == 'HM_Course_Item_Resource_ResourceModel') && $item->module) {
            /** @var HM_Resource_ResourceService $resourceService */
            $resourceService = $this->getService('Resource');

            $resource = $resourceService->getOne($resourceService->find($item->module));

            $this->view->resource = $resource;
            $this->view->iframeUrl = $resourceService->getExternalUrl($resource->resource_id);
        }

        if((get_class($item) == 'HM_Course_Item_File_FileModel') && $item->module) {
            $this->view->iframeUrl = $item->getExecuteUrl();
        }

        $isScormEmulationAllowed = false;

        if ($item && $item->cid) {
            /** @var HM_Course_CourseModel $course */
            $course = $this->getService('Course')->fetchRow(['CID = ?' => $item->cid]);

            if ($course && $course->emulate) {
                $this->getResponse()->setHeader('X-UA-Compatible', 'IE=EmulateIE'.(int) $course->emulate, true);
            }
            $isScormEmulationAllowed = $course->isScormEmulationAllowed();
        }

        /** @var HM_User_UserService $userService */
        $userService = $this->getService('User');

        $currentRole = $userService->getCurrentUserRole();
        $currentId   = $userService->getCurrentUserId();
        
        if($item){
            switch($currentRole){
                case HM_Role_Abstract_RoleModel::ROLE_TEACHER:
                case HM_Role_Abstract_RoleModel::ROLE_LABOR_SAFETY:
                case HM_Role_Abstract_RoleModel::ROLE_LABOR_SAFETY_LOCAL:
                case HM_Role_Abstract_RoleModel::ROLE_DEAN:
                case HM_Role_Abstract_RoleModel::ROLE_DEAN_LOCAL:
                case HM_Role_Abstract_RoleModel::ROLE_MANAGER:
                case HM_Role_Abstract_RoleModel::ROLE_DEVELOPER:
                    break;
                default:
                    if ($this->getService('Acl')->inheritsRole($this->getService('User')->getCurrentUserRole(), HM_Role_Abstract_RoleModel::ROLE_ENDUSER)) {
                        $result = $this->getService('Course')->isStudent($item->cid, $currentId);
                        if($subjectId != 0) $result = $result & $this->getService('Subject')->isStudent($item->cid, $currentId);
                        if($result === false) throw new HM_Permission_Exception(_("Нет прав для доступа к элементу учебного модуля"));
                    } elseif ($this->getService('Acl')->inheritsRole($this->getService('User')->getCurrentUserRole(), HM_Role_Abstract_RoleModel::ROLE_TEACHER)) {
                        $result = $this->getService('Course')->isTeacher($item->cid, $currentId);
                        if($subjectId != 0) $result = $result & $this->getService('Subject')->isTeacher($item->cid, $currentId);
                        if($result === false) throw new HM_Permission_Exception(_("Нет прав для доступа к элементу учебного модуля"));
                    } else {
                        throw new HM_Permission_Exception(_("Нет прав для доступа к элементу учебного модуля"));
                    }
                    break;
            }
            
            if(!($item instanceof HM_Course_Item_Empty_EmptyModel)){
                $data = array('mid'        => $currentId,
                              'cid'        => $item->cid,
                              'date'       => (string) new Zend_Date(),
                              'subject_id' => $subjectId,
                              'item'       => $itemId,
                              'lesson_id'  => $lessonId   
                );

                $this->getService('CourseItemHistory')->insert($data);
                $this->getService('CourseItemCurrent')->updateCurrent($currentId, $subjectId, $item->cid, $itemId, $lessonId);
            }

            $executeUrl = $item->getExecuteUrl();
            $this->view->debug = $executeUrl;
            $this->view->lessonId = $lessonId;
            $this->view->item = $item;
            $this->view->courseId = $item->cid;

            $this->view->executeUrl = false;
            $this->view->emulateScorm = $isScormEmulationAllowed;

            if ($executeUrl !== false) {
                //$this->_redirector->gotoUrl($this->view->baseUrl($executeUrl));
                $this->view->executeUrl = $this->view->baseUrl($executeUrl);
                $lesson = $lessonService->getLesson($lessonId);

                switch($lesson->typeID){
                    case HM_Event_EventModel::TYPE_OLYMPOX_SELFSTUDY:
                        $this->getService('ScormTrack')->insert(array('mid'=>$currentId, 'cid'=>$item->cid, 'lesson_id'=>$lessonId, 'start'=>date('d.m.Y H:i:s'), 'stop'=>date('d.m.Y H:i:s'), 'trackdata'=>'N;'));
                        $this->view->executeUrl = str_replace('index.html', 'index_prepare.html', $this->view->executeUrl);
                    break;
                    case HM_Event_EventModel:: TYPE_OLYMPOX_EXAM:
                        $this->view->executeUrl = str_replace('index.html', 'index_exam.html', $this->view->executeUrl);
                    break;
                }
            }

            // add aicc params
            $separator = '?';
            if (false !== strstr($this->view->executeUrl, $separator)) {
                $separator = '&';
                if (substr($this->view->executeUrl, -1) == '?') {
                    $separator = '';
                }
            }
/*
            $this->view->executeUrl .= $separator . 'aicc_url=' . urlencode($this->view->serverUrl($this->view->url(
                array(
                    'module' => 'course',
                    'controller' => 'api',
                    'action' => 'hacp',
                    'course_id' => $this->view->item->cid,
                    'item_id' => $this->view->item->oid,
                    'module_id' => $this->view->item->module,
                    'lesson_id' => $this->view->lessonId
                )
            )));
*/
            // todo: manage hacp code
            if (false !== strstr($item->getContentType(), HM_Library_Item_FileItemModel::CONTENT_AICC)) {
                //$this->view->executeUrl .= $separator . 'AICC_SID='.$item->module.'&AICC_URL=' . urlencode($this->view->serverUrl('/hacp_datamodel.php?subject_id='.$subjectId.'&lesson_id='.$lessonId));
                //$this->view->executeUrl .= $separator . 'AICC_SID='.$item->module.'&AICC_URL=' . urlencode($this->view->serverUrl($this->view->url(array('action' => 'hacp', 'controller' => 'api', 'module' => 'course', 'subject_id' => $subjectId, 'lesson_id' => $lessonId))));
                $this->view->executeUrl .= $separator . 'AICC_URL=' . urlencode($this->view->serverUrl(self::WRAPPER.$this->view->url(array('action' => 'hacp', 'controller' => 'api', 'module' => 'course', 'subject_id' => $subjectId, 'lesson_id' => $lessonId, 'time' => time())))) . '&AICC_SID='.$item->module;
            }

         
        } else {
            throw new HM_Exception_Data(_('Элемент учебного модуля не найден!'));
        }
        
        
    }
}


