const options = {
  hmToolbarTiny: {
    menubar: false,
    plugins: [
      "template",
      "lists",
      "link",
      "textcolor colorpicker",
      "code",
      "anchor",
      "paste",
      "hr",
      "image",
      "advlist autolink lists link image charmap print preview anchor",
      "searchreplace visualblocks code fullscreen",
      "insertdatetime media table paste code help wordcount"
    ],
    toolbars: [
      [
        "undo",
        "redo",
        "|",
        "pastetext",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        '|',
        'formatselect',
        "|",
        "alignleft",
        "aligncenter",
        "alignright",
        "alignjustify",
        "|",
        "numlist",
        "bullist",
        "|",
        "link",
        "unlink",
        "anchor",
        "|",
        "image",
        "imageupload",
        "blockquote",
        "|",
        "fontsizeselect",
        "|",
        "removeformat",
        "|",
        "table",
        "|",
        "code",
        "|",
        "template"
      ]
    ],
    buttons: ["showCol"]
  },
  hmToolbarMidi: {
    menubar: true,
    plugins: [
      "template",
      "lists",
      "link",
      "textcolor colorpicker",
      "code",
      "anchor",
      "paste",
      "hr",
      "image",
      "advlist autolink lists link image charmap print preview anchor",
      "searchreplace visualblocks code fullscreen",
      "insertdatetime media table paste code help wordcount"
    ],
    toolbars: [
      [
        "undo",
        "redo",
        "|",
        "pastetext",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "subscript",
        "superscript",
        "|",
        "alignleft",
        "aligncenter",
        "alignright",
        "alignjustify",
        "|",
        "h1",
        "h2",
        "h3",
        "h4",
        "|",
        "numlist",
        "bullist",
        "|",
        "link",
        "unlink",
        "anchor",
        "|",
        "image",
        "imageupload",
        "blockQuote",
        "|",
        "divider",
        "|",
        "fontselect",
        "fontsizeselect",
        "forecolor",
        "backcolor",
        "|",
        "removeformat",
        "|",
        "code",
        "|",
        "showCol"
      ]
    ],
    buttons: ["showCol", "h1", "h2", "h3", "h4", "divider", "blockQuote"]
  },
  hmToolbarMaxi: {
    menubar: true,
    plugins: [
      "template",
      "lists",
      "link",
      "textcolor colorpicker",
      "code",
      "anchor",
      "paste",
      "hr",
      "image",
      "advlist autolink lists link image charmap print preview anchor",
      "searchreplace visualblocks code fullscreen",
      "insertdatetime media table paste code help wordcount"
    ],
    toolbars: [
      [
        "undo",
        "redo",
        "|",
        "pastetext",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "subscript",
        "superscript",
        "|",
        "alignleft",
        "aligncenter",
        "alignright",
        "alignjustify",
        "|",
        "h1",
        "h2",
        "h3",
        "h4",
        "|",
        "numlist",
        "bullist",
        "|",
        "link",
        "unlink",
        "anchor",
        "|",
        "image",
        "imageupload",
        "blockQuote",
        "|",
        "divider",
        "|",
        "fontselect",
        "fontsizeselect",
        "forecolor",
        "backcolor",
        "|",
        "removeformat",
        "|",
        "code",
        "|",
        "showCol"
      ]
    ],
    buttons: ["showCol", "h1", "h2", "h3", "h4", "divider", "blockQuote"]
  }
};

export default options;
