/** Названия цветов в designSettings.colors.* в design.ini */
export default {
  buttonBorderLight: "buttonBorderLight",
  buttonBorderDark: "buttonBorderDark",
  buttonDefault: "buttonDefault",
  charts: "charts",
  disabled: "disabled",
  disabledColored: "disabledColored",
  errorBackground: "errorBackground",
  fullscreenBackground: "fullscreenBackground",
  grayDarkest: "grayDarkest",
  grayDarker: "grayDarker",
  grayDark: "grayDark",
  grayBase: "grayBase",
  grayLight: "grayLight",
  grayLightest: "grayLightest",
  gridBackgroundSelected: "gridBackgroundSelected",
  header: "header",
  hintBackground: "hintBackground",
  hintBackgroundBorder: "hintBackgroundBorder",
  iconGray: "iconGray",
  infoBackground: "infoBackground",
  menuBackgroundSelected: "menuBackgroundSelected",
  primaryDark: "primaryDark",
  primaryLight: "primaryLight",
  primarySaturated: "primarySaturated",
  successBackground: "successBackground",
  textContrast: "textContrast",
  textDark: "textDark",
  textDefault: "textDefault",
  textLight: "textLight",
  warningBackground: "warningBackground",
};
