<?php
class HM_Role_Graduated_Csv_CsvModel extends HM_Model_Abstract
{
    public function __get($key)
    {
        $result =  parent::__get($key); // TODO: Change the autogenerated stub
        if ($result === null ) {
            if ($key != 'test_date') {
                $result = '';
            }
        } else {
            if ($key == 'test_date') {
                $result = new DateTime($result);
            }
        }
        return $result;
    }

    public function getName()
    {
        return 'Пользователь: ' . $this->user_fio . '; Курс: ' . $this->subject_code . '; Дата прохождения: ' . $this->test_date->format('d.m.Y');
    }

    public function __toString()
    {
        return $this->getName();
    }

}